"""
Retirement Monte Carlo Simulator
=================================
Simulates randomized retirement scenarios to project portfolio survival,
tax burden, and optimal Roth conversion strategy.

HOW TO USE
----------
1. Edit retirement_config.py to set your parameters (balances, returns,
   spending, Social Security, healthcare scenario, etc.).
2. Run:  python retirement_planning_simulator.py
3. Chart files and an Excel workbook are written to the same folder.

All tunable values live in retirement_config.py.
Do not edit this file for normal planning use.
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.ticker as mticker
from matplotlib.ticker import FuncFormatter
from matplotlib.gridspec import GridSpec

# Import every constant from the config file.
# Star-import is intentional: the simulator references config names directly
# (e.g. MEAN_RETURN, INFLATION) rather than as cfg.MEAN_RETURN, keeping the
# helper functions and simulation loop identical to the single-file version.
from retirement_config import *

# USE_ACA_SUBSIDY is the internal runtime flag that aca_net_premium() and
# optimal_roth_conversion() read. It is set by main() based on SCENARIO_MODE.
# The module-level default matches the single_original (2026+) regime.
USE_ACA_SUBSIDY = False   # overridden in main() — do not set manually here

# Derived constant — keeps ROTH_END_AGE in sync if RMD_START_AGE changes in config
PRICE_RETURN = MEAN_RETURN - DIV_YIELD

# =============================================================================
# SECTION 11 — HELPER FUNCTIONS
# =============================================================================

def smile_expenses(age, base_expenses=None):
    """
    Return real lifestyle spending for the given age, adjusted by the
    retirement spending smile curve (SMILE_REAL_CHANGE).

    No CPI inflation is applied — the result is in today's purchasing power.
    The smile only adjusts the non-healthcare lifestyle component.

    Example: at age 80 the factor is roughly 0.927, so spending = $231,750
    rather than the base $250,000 — about 7% lower in real terms.
    """
    real_factor = 1.0
    for yr in range(START_AGE, age):
        for (s, e), rate in SMILE_REAL_CHANGE.items():
            if s <= yr < e:
                real_factor *= (1 + rate)
                break
    
    base = BASE_EXPENSES if base_expenses is None else base_expenses
    return base * real_factor


def inflate(x, years):
    """
    Grow x at the INFLATION rate for the given number of years.
    Used for Social Security COLA and tax bracket indexing only —
    NOT for living expenses.
    """
    return x * (1 + INFLATION) ** years


def inflate_brackets(brackets, std, years):
    """
    Return inflation-adjusted (brackets, standard_deduction) for a given
    simulation year.  Federal brackets are indexed to INFLATION; Virginia
    brackets are static and do not use this function.
    """
    f = (1 + INFLATION) ** years
    return [(int(t * f), r) for t, r in brackets], int(std * f)


def calc_ordinary_tax(gross_income, brackets, std_ded):
    """
    Federal ordinary income tax on gross income (before standard deduction).
    Applies the MFJ bracket schedule after subtracting the standard deduction.

    This function handles ONLY ordinary income (wages, IRA withdrawals, Roth
    conversions, RMDs, ordinary dividends).  Capital gains are handled
    separately by calc_ltcg_tax().
    """
    taxable = max(0.0, gross_income - std_ded)
    tax = 0.0
    for i, (t, r) in enumerate(brackets):
        nxt = brackets[i + 1][0] if i + 1 < len(brackets) else float("inf")
        if taxable > t:
            tax += (min(taxable, nxt) - t) * r
    return tax


def calc_ltcg_tax(ltcg, ordinary_gross, std_ded, brackets):
    """
    Federal tax on long-term capital gains and qualified dividends.

    LTCG stacks ON TOP of net ordinary income in the LTCG rate schedule.
    That means the 0% LTCG zone is available only to the extent that
    (ordinary_net + LTCG) stays below the first LTCG threshold.

    The LTCG bracket-push effect: as ordinary income rises (e.g., from a
    Roth conversion), it consumes more of the 0% LTCG zone, pushing LTCG
    into the 15% zone.  This is a real incremental cost of converting and
    is correctly accounted for in the Roth optimizer.

    Parameters:
        ltcg            — total capital gains + qualified dividends this year
        ordinary_gross  — gross ordinary income (before standard deduction)
        std_ded         — inflation-adjusted standard deduction
        brackets        — inflation-adjusted LTCG bracket schedule
    """
    ordinary_net = max(0.0, ordinary_gross - std_ded)
    remaining = ltcg
    tax = 0.0
    for i, (t, r) in enumerate(brackets):
        nxt   = brackets[i + 1][0] if i + 1 < len(brackets) else float("inf")
        start = max(t, ordinary_net)      # LTCG starts above ordinary_net
        room  = max(0.0, nxt - start)     # room available in this LTCG bracket
        used  = min(room, remaining)      # LTCG that falls in this bracket
        tax  += used * r
        remaining -= used
        if remaining <= 0:
            break
    return tax


def calc_va_tax(income):
    """
    Virginia state income tax (MFJ).

    Notes:
      - Social Security is fully exempt; exclude SS before calling this.
      - LTCG is taxed as ordinary income (no preferential state rate).
        Pass (ordinary + LTCG) as a single combined income figure.
      - VA brackets are NOT inflation-indexed (thresholds are fixed each year).
    """
    taxable = max(0.0, income - VA_STD_DED_MFJ)
    tax = 0.0
    for i, (t, r) in enumerate(VA_BRACKETS):
        nxt = VA_BRACKETS[i + 1][0] if i + 1 < len(VA_BRACKETS) else float("inf")
        if taxable > t:
            tax += (min(taxable, nxt) - t) * r
    return tax


def calc_ss_taxable(ss, other_income):
    """
    Determine the taxable portion of Social Security benefits using the
    IRS provisional income test (MFJ thresholds).

    Provisional income = other_income + 50% of SS benefits.
      Below $32,000:  0% of SS is taxable
      $32k – $44k:    up to 50% of SS is taxable
      Above $44,000:  up to 85% of SS is taxable (maximum taxable fraction)

    other_income should include ALL non-SS income: RMDs, IRA withdrawals,
    Roth conversions, ordinary dividends, and capital gains.  Including all
    sources is critical — omitting IRA withdrawals would understate SS taxation.
    """
    if ss <= 0:
        return 0.0
    provisional = other_income + 0.5 * ss
    if provisional <= 32_000:
        return 0.0
    elif provisional <= 44_000:
        return min(0.5 * (provisional - 32_000), 0.5 * ss)
    return min(0.85 * ss, 0.85 * (provisional - 44_000) + 6_000)


def aca_net_premium(magi):
    """
    ACA net premium based on the global USE_ACA_SUBSIDY regime:

    USE_ACA_SUBSIDY = True  →  Enhanced rules (ARP 2021 / IRA 2022-2025, EXPIRED):
        Premium = min(8.5% × MAGI, benchmark). No income ceiling.
        Each $1 of Roth conversion raises MAGI and costs 8.5 cents in premium
        while MAGI is below the cap (~$211,765). This is the old behavior.

    USE_ACA_SUBSIDY = False →  Original / 2026+ rules (in effect from Jan 1 2026):
        Eligible only up to 400% FPL (~$81,760 for a couple).
        Above 400% FPL: full benchmark premium — zero subsidy, hard cliff.
        For retirees whose MAGI from capital gains already exceeds $81,760,
        there is no subsidy regardless of Roth conversion amount, so the
        marginal ACA cost of converting is zero (premium is already maxed).
    """
    if magi <= ACA_FPL_2:
        return 0.0
    if USE_ACA_SUBSIDY:
        # Enhanced (expired Dec 31 2025): 8.5% cap, no income ceiling
        return min(0.085 * magi, BENCHMARK_PREMIUM)
    else:
        # Original 2026+ rules: hard cliff at 400% FPL
        fpl_ratio = magi / ACA_FPL_2
        if fpl_ratio >= 4.0:
            return BENCHMARK_PREMIUM   # above cliff — full price, zero subsidy
        # Sliding scale (IRS applicable percentages)
        if   fpl_ratio < 1.33: pct = 0.0206
        elif fpl_ratio < 1.50: pct = 0.0309
        elif fpl_ratio < 2.00: pct = 0.0412
        elif fpl_ratio < 2.50: pct = 0.0619
        elif fpl_ratio < 3.00: pct = 0.0825
        else:                   pct = 0.0996   # 300–400% FPL
        return min(pct * magi, BENCHMARK_PREMIUM)


def irmaa_surcharge(magi):
    """
    Medicare IRMAA (Income-Related Monthly Adjustment Amount) surcharges.

    Returns the annual surcharge for Part B + Part D combined, for a couple.
    These are assessed on income from two years prior (IRMAA lookback).

    Thresholds are for MFJ (2025 values, not inflation-adjusted in model):
      ≤ $212k : no surcharge
      $212k–$266k : +$2,000/yr (couple)
      $266k–$334k : +$4,000/yr
      $334k–$400k : +$6,400/yr
      $400k–$750k : +$11,200/yr
      > $750k     : +$11,200/yr (capped)
    """
    for threshold, surcharge in [
        (212_000,  0),
        (266_000,  2_200),
        (334_000,  4_800),
        (400_000,  7_500),
        (750_000, 10_100),
    ]:
        if magi <= threshold:
            return surcharge
    return 12_800


def calc_niit(ltcg, dividends, magi):
    """
    Net Investment Income Tax (IRC §1411): 3.8% federal surtax on NII
    when MAGI exceeds the MFJ threshold of $250,000.
    Applies to the LESSER of NII or (MAGI - threshold).
    NII = LTCG (gains + qualified dividends) + ordinary dividends.
    IRA/RMD/Roth conversions and Social Security are excluded from NII.
    The threshold is not inflation-adjusted — its real value erodes
    over time, gradually exposing more income to NIIT.
    """
    nii = ltcg + dividends
    if magi <= NIIT_THRESHOLD_MFJ:
        return 0.0
    return NIIT_RATE * min(nii, magi - NIIT_THRESHOLD_MFJ)


# =============================================================================
# SECTION 12 — ROTH CONVERSION OPTIMIZER
# =============================================================================

def optimal_roth_conversion(rmd_ord_div, ord_div, ss, ltcg_fixed, ira_balance,
                             age, brackets, std_ded, ltcg_brackets,
                             use_aca_subsidy=None, irmaa_lookback_magi=0.0):
    """
    Find the largest Roth conversion amount whose marginal all-in cost
    (federal + Virginia + healthcare) stays below MARGINAL_STOP.

    HOW THE OPTIMIZER WORKS
    ───────────────────────
    It steps through conversion amounts from $0 upward, computing the
    incremental cost of each additional $1,000.  It stops when the marginal
    cost of the next $1,000 exceeds MARGINAL_STOP.

    WHY ORDINARY AND LTCG ARE PASSED SEPARATELY
    ─────────────────────────────────────────────
    A Roth conversion is ordinary income — it fills tax brackets from the
    bottom.  LTCG (from selling the taxable account + qualified dividends)
    is fixed for the year and stacks on top at preferential 0%/15%/20% rates.
    Mixing them into one number would tax LTCG at ordinary rates, massively
    overstating the marginal cost and suppressing conversions to near-zero.

    The optimizer also captures the LTCG bracket-push effect: as ordinary
    income rises above the standard deduction, it consumes the 0% LTCG zone,
    pushing existing capital gains from 0% into 15%.  This is a real and
    correctly modeled incremental cost.

    WHY SS IS RE-COMPUTED AT EACH CONVERSION LEVEL
    ────────────────────────────────────────────────
    The taxable portion of Social Security is NOT fixed — it rises with
    income via the IRS provisional income test.  In the phase-in zone
    ($32k–$44k provisional), each $1 of conversion adds $0.50 of taxable SS;
    above $44k provisional, each $1 adds $0.85.  Freezing SS taxable at the
    conv=0 level understates the true marginal cost of converting and causes
    the optimizer to allow too many conversions at ages when SS is in the
    phase-in zone.  Passing ss separately and calling calc_ss_taxable() inside
    total_cost() ensures the correct dynamic SS tax is included at each step.

    WHY IRA WITHDRAWALS ARE NOT INCLUDED IN rmd_ord_div
    ───────────────────────────────────────────────────────
    IRA withdrawals for living expenses happen AFTER the conversion decision.
    Including them in base income would pre-fill brackets and suppress
    conversions during exactly the years when the IRA-to-Roth window is
    most valuable (ages 60–75, before SS and RMDs begin).

    TWO-PASS SEARCH FOR SPEED
    ──────────────────────────
    The IRA can grow to $8–10M before RMDs begin.  A single $1,000-step loop
    would need 8,000–10,000 iterations per call, making 2,000 simulations × 36
    years too slow.  The two-pass approach uses:
      Pass 1: $5,000 steps — ~200 iterations maximum to find approximate boundary
      Pass 2: $1,000 steps — ~10 iterations in the ±$5k neighborhood for precision

    Parameters:
        rmd_ord_div     — RMDs + ordinary dividends (non-SS, non-conversion income)
        ord_div         - ordinary dividends for NIIT calculation
        ss              — full Social Security benefit this year (0 if not yet started)
        ltcg_fixed      — capital gains + qualified dividends (fixed for this year)
        ira_balance     — current IRA balance (conversion cannot exceed this)
        age             — current age (determines healthcare formula)
        brackets        — inflation-adjusted federal ordinary income brackets
        std_ded         — inflation-adjusted standard deduction
        ltcg_brackets   — inflation-adjusted LTCG brackets
        use_aca_subsidy      — override the global USE_ACA_SUBSIDY if provided
        irmaa_lookback_magi  — MAGI from 2 years prior for IRMAA computation
                               (0.0 for pre-Medicare ages, ignored by ACA formula)
    """
    aca_subsidy = USE_ACA_SUBSIDY if use_aca_subsidy is None else use_aca_subsidy

    def total_cost(conv):
        """All-in tax + healthcare cost at a given conversion amount.

        SS taxable is re-computed at each conversion level because the
        provisional income test is income-dependent: more conversion →
        higher provisional income → more SS becomes taxable.
        This correctly captures the marginal SS cost in the phase-in zone.
        """
        # Re-compute SS taxable at this conversion level
        other_for_ss = rmd_ord_div + conv + ltcg_fixed
        ss_tax   = calc_ss_taxable(ss, other_for_ss)
        ordinary = rmd_ord_div + conv + ss_tax
        fed  = calc_ordinary_tax(ordinary, brackets, std_ded)
        fed += calc_ltcg_tax(ltcg_fixed, ordinary, std_ded, ltcg_brackets)
        # Include Virginia tax so the stop threshold reflects the combined
        # federal + state marginal rate (22% fed + 5.75% VA = 27.75%)
        # All SS benefits are exempted from VA taxes
        va   = calc_va_tax(ordinary + ltcg_fixed - ss_tax)
        magi = ordinary + ltcg_fixed
        # NIIT: Roth conversion is not NII, but pushes MAGI over $250k,
        # exposing existing NII (ltcg_fixed) to 3.8%.
        # niit = calc_niit(ltcg_fixed, 0.0, magi)
        # Pass ord_div alongside ltcg_fixed
        niit = calc_niit(ltcg_fixed, ord_div, magi)

        if age >= MEDICARE_AGE:
            # Use the 2-year lookback MAGI for IRMAA (SSA rule),
            # passed in from the simulation loop.
            health = MEDICARE_BASE + irmaa_surcharge(irmaa_lookback_magi)
        elif aca_subsidy:
            health = aca_net_premium(magi)     # income-linked: 0–8.5% of MAGI
        else:
            health = BENCHMARK_PREMIUM         # flat full-price: no marginal surcharge
        return fed + niit + va + health

    # ── Pass 1: coarse $5,000 steps ─────────────────────────────────────────
    coarse = 5_000
    best   = 0
    prev   = total_cost(0)
    for conv in range(coarse, int(ira_balance) + coarse, coarse):
        c = total_cost(conv)
        if (c - prev) / coarse > MARGINAL_STOP:
            break                    # marginal rate exceeded — stop here
        prev = c
        best = conv                  # this level is still acceptable

    # ── Pass 2: fine $1,000 steps around the coarse boundary ─────────────────
    fine_lo = max(0, best - coarse)
    best    = fine_lo
    prev    = total_cost(fine_lo)
    fine_hi = min(fine_lo + 2 * coarse + 1_000, int(ira_balance) + 1_000)
    for conv in range(fine_lo + 1_000, fine_hi, 1_000):
        c = total_cost(conv)
        if (c - prev) / 1_000 > MARGINAL_STOP:
            break
        prev = c
        best = conv

    return best


# =============================================================================
# SECTION 13 — MONTE CARLO SIMULATION ENGINE
# =============================================================================

def run_simulation(scenario_label="Baseline"):
    """
    Run SIMS independent retirement scenarios and return a DataFrame with
    one row per (simulation, age) pair — SIMS × (END_AGE − START_AGE + 1) rows.

    WITHIN EACH YEAR, the sequence of events is:
      1. Compute inflation-indexed values (expenses, SS, tax brackets)
      2. Taxable account pays dividends (automatically recognized income)
      3. Compute RMD if age ≥ RMD_START_AGE (= 75 for born 1960+; 73 for 1951-1959))
      4. Decide Roth conversion (optimizer, ages 60–75 only)
      5. Fund lifestyle expenses from waterfall: cash → taxable → IRA → Roth
      6. Compute all taxes (federal ordinary, federal LTCG, Virginia, SS provisional)
      7. Compute healthcare cost (ACA or Medicare + IRMAA)
      8. Pay taxes+health from waterfall: cash → taxable → IRA → Roth
      9. Apply investment returns to taxable (price-only), IRA, and Roth
     10. Record all values for this year

    NOTE: The global USE_ACA_SUBSIDY controls which healthcare formula is used
    in both the optimizer (step 4) and the actual healthcare charge (step 7).
    Change it before calling run_simulation() to switch scenarios.
    """
    np.random.seed(SEED)
    years   = END_AGE - START_AGE + 1

    # ── Generate return matrix: lognormal model ─────────────────────────────
    # Lognormal is the correct model for investment returns:
    #   - Always > -100%: no impossible outcomes (no artificial floor needed,
    #     though CRASH_FLOOR is retained as a practical safety clip)
    #   - Log-returns are normal and self-consistent across time horizons
    #   - Right-skewed: matches empirical equity return distributions
    #
    # Parameterization: MEAN_RETURN and VOL_RETURN are the arithmetic mean
    # and std dev of simple annual returns. Converted to lognormal mu/sigma:
    #   sigma² = log(1 + VOL² / (1 + MEAN)²)
    #   mu     = log(1 + MEAN) - 0.5 * sigma²
    # This ensures the lognormal distribution has exactly the specified
    # arithmetic mean and standard deviation.
    #
    # r_price decomposition: (1 + r_total) = (1 + r_price) * (1 + DIV_YIELD)
    # Rearranging: r_price = (1 + r_total) / (1 + DIV_YIELD) - 1
    # This correctly separates price return from dividend yield at every
    # return level (unlike linear scaling which breaks at extreme returns).

    sigma2      = np.log(1 + (VOL_RETURN**2) / (1 + MEAN_RETURN)**2)
    sigma       = np.sqrt(sigma2)
    mu_log      = np.log(1 + MEAN_RETURN) - 0.5 * sigma2
    log_returns = np.random.normal(mu_log, sigma, (SIMS, years))
    r_total     = np.clip(np.exp(log_returns) - 1, CRASH_FLOOR, None)
    r_price     = (1 + r_total) / (1 + DIV_YIELD) - 1

    rows = []

    for sim in range(SIMS):
        # Each simulation starts with the same initial balances
        cash, taxable, ira, roth = CASH_START, TAXABLE_START, IRA_START, ROTH_START
        # Running cost basis of the taxable account. Initialized from COST_BASIS_PCT.
        # Reduced proportionally whenever shares are sold; unchanged by price gains.
        taxable_basis = TAXABLE_START * COST_BASIS_PCT
        # IRMAA is assessed on MAGI from 2 years prior (SSA lookback rule).
        magi_history  = [0.0] * years   # index i = MAGI at simulation year i

        for i, age in enumerate(range(START_AGE, END_AGE + 1)):

            # ── Step 1: Inflation-indexed values for this year ────────────────
            # Expenses use the real spending smile (no inflation).
            # SS inflates for COLA. Tax brackets inflate for bracket indexing.
            #expenses  = smile_expenses(age)
            expenses  = smile_expenses(age, BASE_EXPENSES)
            #ss        = inflate(SS_AMOUNT, i) if age >= SS_START_AGE else 0.0
            ss = SS_AMOUNT if age >= SS_START_AGE else 0.0
            brackets, std = inflate_brackets(BASE_BRACKETS_2025, STD_DED_2025, i)
            ltcg_bkts, _ = inflate_brackets(LTCG_BRACKETS_2025, 0, i)

            # ── Step 2: Dividend income from taxable account ──────────────────
            # Dividends are generated automatically by the portfolio each year.
            # They are split into ordinary (taxed at bracket rates) and
            # qualified (taxed at preferential LTCG rates).
            # Dividends are deposited to the cash account — this is how a
            # brokerage account works: distributions land in the settlement
            # account each quarter whether or not you reinvest them.
            # The taxable account grows at PRICE_RETURN (= MEAN_RETURN - DIV_YIELD)
            # which already excludes the dividend component, so adding dividends
            # to cash here is correct and avoids double-counting.
            dividends = taxable * DIV_YIELD
            ord_div   = dividends * (1 - QUAL_DIV_PCT)   # ordinary dividend income
            qual_div  = dividends * QUAL_DIV_PCT          # qualified dividend income
            cash     += dividends                         # dividends land in cash account

            # ── Step 3: Required Minimum Distribution (age 73+) ──────────────
            # IRS mandates a minimum annual withdrawal from pre-tax accounts.
            # The RMD is computed from the IRS Uniform Lifetime Table factor.
            # RMD goes directly to cash (it is ordinary income when received).
            rmd = 0.0
            if age >= RMD_START_AGE:
                rmd   = min(ira / RMD_TABLE.get(age, 8.9), ira)
                ira  -= rmd
                cash += rmd

            # ── Step 4: Roth conversion decision (ages 60–72 only) ───────────
            # Estimate LTCG from taxable sales needed to cover expenses.
            # This is passed to the optimizer separately from ordinary income
            # because LTCG is taxed at preferential rates, not bracket rates.
            expected_sold = min(taxable, max(0.0, expenses - ss - cash))
            # Dynamic gain fraction: as price return grows the account without
            # growing the basis, the taxable gain fraction rises over time.
            gain_frac_est = (1.0 - taxable_basis / taxable) if taxable > 0 else (1.0 - COST_BASIS_PCT)
            expected_ltcg = expected_sold * gain_frac_est + qual_div

            # Base ordinary income = income we KNOW is already recognized
            # this year, before any conversion amount is decided.
            # Critically, we do NOT include expected IRA withdrawals — those
            # are a consequence of expenses that happen after the conversion,
            # and including them would incorrectly suppress conversion headroom.
            # rmd_ord_div: non-SS, non-conversion ordinary income known at decision time.
            # ss is passed separately so the optimizer re-computes the taxable SS
            # fraction at each conversion level (it rises with income via the
            # provisional income test — freezing it at conv=0 understates cost).
            rmd_ord_div = rmd + ord_div

            roth_conv = 0.0
            if age <= ROTH_END_AGE and ira > 0:
                # Pass the 2-year lookback MAGI so the optimizer uses
                # the correct IRMAA tier when deciding how much to convert.
                irmaa_opt_magi = magi_history[i - 2] if i >= 2 else 0.0
                raw_conv = min(
                    optimal_roth_conversion(
                        rmd_ord_div, ord_div, ss, expected_ltcg, ira,
                        age, brackets, std, ltcg_bkts,
                        irmaa_lookback_magi=irmaa_opt_magi,
                    ),
                    ira,
                )  # uses global USE_ACA_SUBSIDY

                # ── Tax-capacity cap ─────────────────────────────────────────
                # The optimizer assumes conversion tax is paid from cash or
                # taxable assets held outside the IRA. When those are gone,
                # the IRA must fund its own tax bill — a recursive tax-on-tax
                # loop where drawing IRA to pay tax generates more tax, requiring
                # more IRA draws. This inflates the effective cost well above
                # MARGINAL_STOP and produces unrealistically large IRA withdrawals.
                #
                # When non-IRA liquid assets (cash + taxable) are insufficient
                # to cover the estimated tax bill, binary-search for the largest
                # conversion whose tax can actually be funded without the IRA.
                # Non-IRA sources that can fund the tax bill without
                # creating recursive additional tax:
                #   cash    — no tax impact
                #   taxable — generates LTCG but handled in step 8 iteration
                #   roth    — tax-free withdrawals, no income generated
                # IRA draws to fund taxes generate MORE taxable income,
                # creating the recursive tax-on-tax loop we want to prevent.
                non_ira_liquid = cash + taxable + roth   # available BEFORE step 5
                if raw_conv > 0:
                    # Estimate tax on the raw conversion amount
                    ss_t_est   = calc_ss_taxable(ss, rmd_ord_div + raw_conv + expected_ltcg)
                    ord_est    = rmd_ord_div + raw_conv + ss_t_est
                    magi_est   = ord_est + expected_ltcg
                    fed_est    = (calc_ordinary_tax(ord_est, brackets, std)
                                  + calc_ltcg_tax(expected_ltcg, ord_est, std, ltcg_bkts))
                    va_est     = calc_va_tax(ord_est + expected_ltcg - ss_t_est)
                    niit_est   = calc_niit(expected_ltcg, ord_div, magi_est)
                    h_est      = (MEDICARE_BASE + irmaa_surcharge(irmaa_opt_magi)
                                  if age >= MEDICARE_AGE else aca_net_premium(magi_est))
                    tax_est    = fed_est + va_est + niit_est + h_est
                    # Cash also needs to cover living expenses after SS
                    needed     = max(0.0, smile_expenses(age) - ss) + tax_est

                    if non_ira_liquid < needed:
                        # Binary-search: largest conversion coverable by non-IRA assets
                        lo, hi = 0, raw_conv
                        for _ in range(20):
                            mid = (lo + hi) // 1_000 * 1_000
                            if mid == lo:
                                break
                            ss_t   = calc_ss_taxable(ss, rmd_ord_div + mid + expected_ltcg)
                            ord_m  = rmd_ord_div + mid + ss_t
                            magi_m = ord_m + expected_ltcg
                            fed_m  = (calc_ordinary_tax(ord_m, brackets, std)
                                      + calc_ltcg_tax(expected_ltcg, ord_m, std, ltcg_bkts))
                            va_m   = calc_va_tax(ord_m + expected_ltcg - ss_t)
                            niit_m = calc_niit(expected_ltcg, ord_div, magi_m)
                            h_m    = (MEDICARE_BASE + irmaa_surcharge(irmaa_opt_magi)
                                      if age >= MEDICARE_AGE else aca_net_premium(magi_m))
                            tax_m  = fed_m + va_m + niit_m + h_m
                            need_m = max(0.0, smile_expenses(age) - ss) + tax_m
                            if non_ira_liquid >= need_m:
                                lo = mid
                            else:
                                hi = mid
                        raw_conv = lo

                roth_conv = raw_conv
                ira  -= roth_conv   # moved out of pre-tax IRA
                roth += roth_conv   # landed in tax-free Roth (taxes paid separately)

            # ── Step 5: Fund lifestyle expenses ──────────────────────────────
            # Waterfall: most liquid and tax-efficient sources drawn first.
            # SS offsets the need before any portfolio withdrawal.
            # Roth is drawn last to preserve tax-free compound growth.
            needed    = max(0.0, expenses - ss)
            used_cash = min(cash, needed);    cash    -= used_cash;    needed -= used_cash
            sold_tax  = min(taxable, needed)
            if sold_tax > 0 and taxable > 0:
                gain_frac_5    = 1.0 - taxable_basis / taxable   # gain fraction at time of sale
                ltcg_from_sold = sold_tax * gain_frac_5          # LTCG this sale generates
                taxable_basis -= (sold_tax / taxable) * taxable_basis   # reduce basis proportionally
            else:
                ltcg_from_sold = 0.0
            taxable -= sold_tax;     needed -= sold_tax
            ira_wd    = min(ira, needed);     ira     -= ira_wd;       needed -= ira_wd
            roth_wd   = min(roth, needed);    roth    -= roth_wd
            # If needed > 0 after Roth, the household is insolvent (all accounts empty)

            # ── Steps 6–8: Compute taxes, healthcare, and pay — iteratively ──────
            #
            # Steps 6, 7, and 8 are combined into a single iterative loop
            # because they are mutually dependent:
            #   - Selling taxable in step 8 generates LTCG → changes tax bill
            #   - Drawing IRA in step 8 is ordinary income → changes tax + SS taxable
            #   - More tax → may require more sales → more LTCG → more tax ...
            #
            # The iteration converges in 3–5 steps because each marginal sale
            # generates tax at a rate < 100%, so the series is contracting.
            #
            # Variables accumulated across iterations:
            #   extra_sold   — additional taxable sold in step 8 (beyond step 5)
            #   extra_ira_wd — additional IRA drawn in step 8 (beyond step 5)
            # These are added to the step 5 amounts when recording the final row.

            extra_sold     = 0.0   # extra taxable sold to cover tax shortfall
            extra_ira_wd   = 0.0   # extra IRA drawn to cover tax shortfall
            new_extra_roth = 0.0   # extra Roth drawn tax-free to pay taxes

            for _iter in range(15):

                # ── Step 6: Recompute tax on all income including step-8 sales ─
                # Total taxable sales this year = step-5 amount + step-8 extra
                total_sold  = sold_tax + extra_sold
                # Total IRA withdrawal = step-5 amount + step-8 extra
                total_ira_wd = ira_wd + extra_ira_wd

                # Dynamic gain fraction based on current taxable account state.
                # Computed once per iteration before any income aggregation.
                gain_frac = ((taxable - taxable_basis) / taxable
                             if taxable > 0 else 0.0)

                # SS provisional income: include ALL non-SS income flowing through MAGI.
                # Qualified dividends are LTCG-rate income but still part of AGI,
                # so they count toward provisional income under IRS Publication 915.
                other_for_ss   = (rmd + roth_conv + total_ira_wd + ord_div
                                  + total_sold * gain_frac
                                  + qual_div)
                ss_taxable     = calc_ss_taxable(ss, other_for_ss)

                ordinary_gross = rmd + roth_conv + total_ira_wd + ss_taxable + ord_div
                ltcg           = ltcg_from_sold + qual_div   # dynamic: actual gain from sales
                magi           = ordinary_gross + ltcg

                fed_tax  = calc_ordinary_tax(ordinary_gross, brackets, std)
                fed_tax += calc_ltcg_tax(ltcg, ordinary_gross, std, ltcg_bkts)
                # NIIT (IRC §1411): 3.8% on NII when MAGI > $250k.
                # NII = LTCG + all dividends (not IRA/RMD/SS).
                # NIIT: NII = LTCG (includes qual_div gains) + all dividends
                # NII = ltcg_from_sold + qual_div + ord_div = all investment income.
                # niit     = calc_niit(ltcg, ord_div + qual_div, magi)
                niit     = calc_niit(ltcg, ord_div, magi)
                va_tax   = calc_va_tax(rmd + roth_conv + total_ira_wd + ord_div + ltcg)
                total_tax = fed_tax + niit + va_tax

                # ── Step 7: Healthcare cost ────────────────────────────────────
                if age >= MEDICARE_AGE:
                    irmaa_magi = magi_history[i - 2] if i >= 2 else 0.0
                    health = MEDICARE_BASE + irmaa_surcharge(irmaa_magi)
                elif USE_ACA_SUBSIDY:
                    health = aca_net_premium(magi)
                else:
                    health = BENCHMARK_PREMIUM

                # ── Step 8: Pay — waterfall with convergence check ─────────────
                due = total_tax + health
                cash_used  = min(cash, due)
                shortfall  = due - cash_used

                if shortfall < 0.01:
                    # Cash covers the entire bill — no asset sales needed
                    cash -= cash_used
                    break

                # Fill shortfall: taxable → Roth → IRA
                # Roth is used BEFORE IRA for tax payments because Roth WDs are
                # tax-free — they add no ordinary income, breaking the recursive
                # loop where IRA draws generate more tax requiring more IRA draws.
                new_extra_sold   = min(taxable, shortfall)
                if new_extra_sold > extra_sold and taxable > 0:   # incremental sale this iter
                    inc = new_extra_sold - extra_sold
                    gain_frac_8     = 1.0 - taxable_basis / taxable
                    ltcg_from_sold += inc * gain_frac_8            # accumulate LTCG
                    taxable_basis  -= (inc / taxable) * taxable_basis
                shortfall       -= new_extra_sold
                new_extra_roth   = min(roth, shortfall)   # tax-free — preferred over IRA
                shortfall       -= new_extra_roth
                new_extra_ira_wd = min(ira - extra_ira_wd, shortfall)  # last resort
                shortfall       -= new_extra_ira_wd

                # Check convergence: did the extra sales change from last iteration?
                if (abs(new_extra_sold   - extra_sold)   < 1.0 and
                    abs(new_extra_ira_wd - extra_ira_wd) < 1.0):
                    # Converged — apply the final amounts
                    extra_sold    = new_extra_sold
                    extra_ira_wd  = new_extra_ira_wd
                    cash         -= cash_used
                    taxable      -= extra_sold
                    roth         -= new_extra_roth   # tax-free; drawn before IRA
                    ira          -= extra_ira_wd     # last resort; only if Roth exhausted
                    break

                extra_sold   = new_extra_sold
                extra_ira_wd = new_extra_ira_wd

            # Update the step-5 totals so the recorded row reflects everything
            sold_tax  += extra_sold    # total taxable sold this year (steps 5 + 8)
            ira_wd    += extra_ira_wd  # total IRA withdrawn this year (steps 5 + 8)
            roth_wd   += new_extra_roth  # step-8 Roth drawn tax-free to pay taxes
            magi_history[i] = magi     # record for IRMAA lookback


            # ── Step 9: Apply end-of-year investment returns ──────────────────
            # Taxable grows at price-only return (dividends already extracted above).
            # IRA and Roth grow at the full total return (dividends reinvested).
            # Cash earns nothing (conservative assumption).
            taxable       *= (1 + r_price[sim, i])
            # taxable_basis unchanged — price appreciation is unrealized gain on top of basis
            ira     *= (1 + r_total[sim, i])
            roth    *= (1 + r_total[sim, i])

            # ── Step 10: Record year-end snapshot ────────────────────────────
            rows.append({
                "Sim":           sim + 1,
                "Age":           age,
                # Account balances (end of year, after returns)
                "Portfolio":     cash + taxable + ira + roth,
                "Cash":          cash,
                "Taxable":       taxable,
                "IRA":           ira,
                "Roth":          roth,
                # Income sources
                "SS":            ss,
                "RMD":           rmd,
                "Roth Conv":     roth_conv,
                "Taxable Sold":  sold_tax,
                "IRA WD":        ira_wd,
                "Roth WD":       roth_wd,
                "Ord Div":       ord_div,
                "Qual Div":      qual_div,
                # Tax inputs
                "Ordinary":      ordinary_gross,
                "LTCG":          ltcg,
                "MAGI":          magi,
                "SS Taxable":    ss_taxable,
                # Tax outputs
                "Fed Tax":       fed_tax,
                "VA Tax":        va_tax,
                "NIIT":          niit,                 
                "Tax":           total_tax,
                "Health":        health,
                # Spending
                "Expenses":      expenses,
                "Taxable Income": ordinary_gross + ltcg,
            })

    return pd.DataFrame(rows)

# =============================================================================
# SECTION 14 — CHART FORMATTING HELPERS
# =============================================================================

# Axis formatters — convert raw numbers to human-readable labels
fmt_k   = FuncFormatter(lambda x, _: f"${x/1e3:,.0f}k")    # e.g. 250000 → "$250k"
fmt_m   = FuncFormatter(lambda x, _: f"${x/1e6:,.1f}M")    # e.g. 6300000 → "$6.3M"
fmt_pct = FuncFormatter(lambda x, _: f"{x:.0%}")            # e.g. 0.991 → "99%"

def grid(ax, axis="y"):
    """Apply consistent light dashed gridlines to an axes object."""
    ax.grid(True, axis=axis, color=GRID_CLR, linestyle="--", linewidth=0.7, alpha=0.8)
    ax.set_axisbelow(True)

def add_milestones(ax):
    """
    Annotate key retirement milestones with vertical dotted lines.
    Called after data is plotted so get_ylim() returns the correct range.
    Text is placed near the top of the chart area.
    """
    ymin, ymax = ax.get_ylim()
    ypos = ymin + (ymax - ymin) * 0.97
    for m_age, label in [(65, "Medicare"), (70, "SS"), (RMD_START_AGE, "RMDs")]:
        ax.axvline(m_age, color=C_GRAY, lw=0.9, ls=":")
        ax.text(m_age + 0.2, ypos, label, fontsize=7.5, color=C_GRAY, va="top")

def save_chart(fig, filename, chart_num):
    """
    Save a figure to disk with error handling and full path reporting.
    Uses subplots_adjust instead of tight_layout to avoid the known
    matplotlib conflict between tight_layout and twinx axes.
    """
    path = os.path.abspath(filename)

    # Delete the file if exists before saving with the same name
    if os.path.exists(filename):
        os.remove(filename)

    try:
        fig.savefig(path, dpi=150, bbox_inches="tight")
        print(f"Chart {chart_num} saved: {path}")
    except Exception as e:
        print(f"Chart {chart_num} FAILED to save: {e}")
    finally:
        plt.close(fig)


# =============================================================================
# SECTION 15 — CHART 1: MONTE CARLO FAN
# =============================================================================

def chart1_fan(summary):
    """
    Monte Carlo fan chart showing the spread of all 2,000 portfolio outcomes.

    Displays:
      - Shaded bands for 10th–90th and 25th–75th percentile ranges
      - Median and mean portfolio paths
      - Portfolio survival rate on a right-side axis (% of sims still solvent)
      - Vertical milestone lines for Medicare, SS, and RMD start ages

    Uses Scenario A (subsidized ACA) summary data.
    """
    fig, ax = plt.subplots(figsize=(11, 6.5))
    fig.patch.set_facecolor("#F8F9FA"); ax.set_facecolor("#F8F9FA")

    ages = summary["Age"]

    # Shaded probability bands
    ax.fill_between(ages, summary["P10"], summary["P90"],
                    color=C_BLUE, alpha=0.15, label="10th-90th Pctile")
    ax.fill_between(ages, summary["P25"], summary["P75"],
                    color=C_BLUE, alpha=0.28, label="25th-75th Pctile")
    ax.plot(ages, summary["P10"],    color=C_BLUE,   lw=0.8, ls="--", alpha=0.5)
    ax.plot(ages, summary["P90"],    color=C_BLUE,   lw=0.8, ls="--", alpha=0.5)
    ax.plot(ages, summary["Median"], color=C_BLUE,   lw=2.5, label="Median")
    ax.plot(ages, summary["Mean"],   color=C_ORANGE, lw=1.5, ls=":",  label="Mean")

    # Survival rate on right axis
    ax2 = ax.twinx()
    ax2.plot(ages, summary["Survival"], color=C_RED, lw=2.0, ls="-.", label="Survival Rate")
    ax2.set_ylim(0, 1.15); ax2.yaxis.set_major_formatter(fmt_pct)
    ax2.set_ylabel("Survival Rate", color=C_RED, fontsize=10)
    ax2.tick_params(axis="y", colors=C_RED)

    ax.yaxis.set_major_formatter(fmt_m)
    ax.set_xlabel("Age", fontsize=11)
    ax.set_ylabel("Portfolio Value  (Real 2025 $)", fontsize=11)
    ax.set_title(
        f"Monte Carlo Retirement Projection  |  {SIMS:,} Simulations  |  Ages {START_AGE}-{END_AGE}",
        fontsize=12, fontweight="bold", pad=12)
    ax.set_xlim(START_AGE, END_AGE)
    add_milestones(ax)

    # Combine legends from both axes
    l1, lb1 = ax.get_legend_handles_labels()
    l2, lb2 = ax2.get_legend_handles_labels()
    ax.legend(l1+l2, lb1+lb2, loc="upper right", fontsize=9, framealpha=0.9)
    grid(ax)

    # subplots_adjust avoids the tight_layout / twinx incompatibility
    fig.subplots_adjust(left=0.08, right=0.88, top=0.92, bottom=0.08)
    #save_chart(fig, "chart1_montecarlo.png", 1)
    return fig


# =============================================================================
# SECTION 16 — CHART 2: MEDIAN PATH DETAIL (3-PANEL)
# =============================================================================

def chart2_median(df_med, filename="chart2_median_detail.png", subtitle="Median Path"):
    """
    Three-panel breakdown of the median simulation path.

    Panel 1 — Funding Sources vs. Expenses:
        Stacked bars show where money comes from each year:
        SS (green), Taxable Sales (teal), Roth Conv (purple), IRA WD (orange),
        RMD (red), Roth WD (cyan).  The dashed line is the spending target.
        This panel clearly shows the Roth conversion window (ages 60–72) and
        when each account type is drawn upon.

    Panel 2 — Portfolio Composition:
        Stacked area chart of account balances over time.  Shows how the mix
        shifts from IRA-heavy at 60 to Roth-dominant by the late 80s.

    Panel 3 — Taxes, Healthcare & Effective Rates:
        Stacked bars: federal tax (red), Virginia tax (orange), healthcare (purple).
        Overlaid lines: effective rates as % of total spending and taxable income.
        The spike at ages 73+ reflects RMDs driving up ordinary income.

    Parameters:
        df_med    — median-path DataFrame (one row per age)
        filename  — output filename (allows two versions: subsidized vs no-subsidy)
        subtitle  — scenario label shown in the chart title
    """
    fig = plt.figure(figsize=(13, 16)); fig.patch.set_facecolor("#F8F9FA")
    gs  = GridSpec(3, 1, figure=fig, hspace=0.40)
    ax1 = fig.add_subplot(gs[0]); ax2 = fig.add_subplot(gs[1]); ax3 = fig.add_subplot(gs[2])
    for ax in [ax1, ax2, ax3]: ax.set_facecolor("#F8F9FA")

    fig.suptitle(f"Median Path — Retirement Breakdown  (Real 2025 $)  |  {subtitle}",
                 fontsize=13, fontweight="bold", y=0.995)
    ages = df_med["Age"].values

    # ── Panel 1: Funding Sources ─────────────────────────────────────────────
    # Running bottoms for stacked bars
    b0 = df_med["SS"]
    b1 = b0 + df_med["Taxable Sold"]
    b2 = b1 + df_med["Roth Conv"]
    b3 = b2 + df_med["IRA WD"]
    b4 = b3 + df_med["RMD"]

    ax1.bar(ages, df_med["SS"],           color=C_GREEN,  label="Social Security",           alpha=0.9)
    ax1.bar(ages, df_med["Taxable Sold"], bottom=b0,       color=C_TEAL,   label="Taxable Sold",     alpha=0.9)
    ax1.bar(ages, df_med["Roth Conv"],    bottom=b1,       color=C_PURPLE, label="Roth Conv (tax event)", alpha=0.9)
    ax1.bar(ages, df_med["IRA WD"],       bottom=b2,       color=C_ORANGE, label="IRA Withdrawal",   alpha=0.9)
    ax1.bar(ages, df_med["RMD"],          bottom=b3,       color=C_RED,    label="RMD",              alpha=0.9)
    ax1.bar(ages, df_med["Roth WD"],      bottom=b4,       color=C_CYAN,   label="Roth WD (tax-free)", alpha=0.9)
    ax1.plot(ages, df_med["Expenses"], color="black", lw=2, ls="--",
             label="Lifestyle Expenses (real $)", zorder=5)

    ax1.yaxis.set_major_formatter(fmt_k)
    ax1.set_title("Funding Sources vs. Expenses", fontsize=11, fontweight="bold")
    ax1.legend(loc="upper right", fontsize=8, ncol=2, framealpha=0.85)
    grid(ax1); ax1.set_xlim(START_AGE-0.5, END_AGE+0.5); add_milestones(ax1)

    # ── Panel 2: Portfolio Composition ──────────────────────────────────────
    ax2.stackplot(ages,
                  df_med["Cash"], df_med["Taxable"], df_med["IRA"], df_med["Roth"],
                  labels=["Cash", "Taxable", "IRA / Pre-Tax", "Roth"],
                  colors=[C_TEAL, C_BLUE, C_ORANGE, C_GREEN], alpha=0.85)
    ax2.yaxis.set_major_formatter(fmt_m)
    ax2.set_title("Portfolio Composition Over Time", fontsize=11, fontweight="bold")
    ax2.legend(loc="upper left", fontsize=9)
    grid(ax2); ax2.set_xlim(START_AGE-0.5, END_AGE+0.5); add_milestones(ax2)

    # ── Panel 3: Taxes, Healthcare & Effective Rates ─────────────────────────
    ax3r = ax3.twinx()    # right axis for rate lines

    ax3.bar(ages, df_med["Fed Tax"],
            color=C_RED,    label="Federal Tax",   alpha=0.85)
    ax3.bar(ages, df_med["VA Tax"],
            bottom=df_med["Fed Tax"],
            color=C_ORANGE, label="Virginia Tax",  alpha=0.85)
    ax3.bar(ages, df_med["Health"],
            bottom=df_med["Fed Tax"] + df_med["VA Tax"],
            color=C_PURPLE, label="Healthcare",    alpha=0.85)

    # Effective rate lines: total burden as % of expenses and as % of taxable income
    burden  = df_med["Tax"] + df_med["Health"]
    ti      = df_med["Taxable Income"].replace(0, np.nan)
    r_spend = burden / df_med["Expenses"]
    r_tax   = np.where(ti >= 20_000, burden / ti, np.nan)  # suppress near-zero income

    l1, = ax3r.plot(ages, r_spend, color=C_BLUE,  lw=2.2, label="(Tax+Health) / Expenses")
    l2, = ax3r.plot(ages, r_tax,   color=C_GREEN, lw=2.2, ls="--", label="(Tax+Health) / Taxable Income")

    ax3.yaxis.set_major_formatter(fmt_k); ax3.set_ylabel("Annual Cost ($)", fontsize=9)
    ax3r.set_ylim(0, 0.60); ax3r.yaxis.set_major_formatter(fmt_pct)
    ax3r.set_ylabel("Effective Rate", fontsize=9, color=C_BLUE)
    ax3r.tick_params(axis="y", colors=C_BLUE)
    ax3.set_title("Taxes, Healthcare & Effective Rates", fontsize=11, fontweight="bold")
    ax3.set_xlabel("Age", fontsize=10)

    bar_h = [mpatches.Patch(color=C_RED,    label="Federal Tax"),
             mpatches.Patch(color=C_ORANGE, label="Virginia Tax"),
             mpatches.Patch(color=C_PURPLE, label="Healthcare")]
    ax3r.legend(handles=bar_h+[l1,l2], loc="upper right", fontsize=8, framealpha=0.9)
    grid(ax3); ax3.set_xlim(START_AGE-0.5, END_AGE+0.5); add_milestones(ax3)

    #save_chart(fig, filename, "2")
    return fig


# =============================================================================
# SECTION 17 — CHART 3: PERCENTILE SCENARIO PATHS
# =============================================================================

def chart3_paths(df):
    """
    Show five individual simulation paths selected at fixed percentiles of the
    terminal portfolio value: P10, P25, P50, P75, P90.

    Unlike the fan chart (which shows statistical bands), each line here is
    internally consistent — it is a single simulation's full history.  This
    makes it easier to see how bad sequences of returns compound over time
    in the pessimistic scenarios.

    Left panel:  portfolio value for each scenario path
    Right panel: annual tax + healthcare cost for each scenario path
                 (shows how RMDs and IRMAA drive up costs in good scenarios)
    """
    fig, axes = plt.subplots(1, 2, figsize=(14, 6))
    fig.patch.set_facecolor("#F8F9FA")
    fig.suptitle("Percentile Retirement Scenarios  (Real 2025 $)", fontsize=13, fontweight="bold")

    # Select the representative simulation for each percentile
    terminal = df.groupby("Sim")["Portfolio"].last().sort_values()
    n = len(terminal)
    pct_map = {10: int(n*0.10), 25: int(n*0.25), 50: int(n*0.50),
               75: int(n*0.75), 90: int(n*0.90)}
    colors  = {10: C_RED, 25: C_ORANGE, 50: C_BLUE, 75: C_GREEN, 90: C_TEAL}

    for ax in axes: ax.set_facecolor("#F8F9FA")
    ax_p, ax_t = axes

    for pct, idx in pct_map.items():
        sim_df = df[df["Sim"] == terminal.index[idx]]
        lw = 2.2 if pct == 50 else 1.3   # median path drawn thicker
        ax_p.plot(sim_df["Age"], sim_df["Portfolio"],
                  color=colors[pct], lw=lw, label=f"P{pct}")
        ax_t.plot(sim_df["Age"], sim_df["Tax"] + sim_df["Health"],
                  color=colors[pct], lw=lw, label=f"P{pct}")

    ax_p.yaxis.set_major_formatter(fmt_m)
    ax_p.set_title("Portfolio Value by Scenario", fontsize=11, fontweight="bold")
    ax_p.set_xlabel("Age"); ax_p.set_ylabel("Portfolio (Real $)")
    ax_p.legend(fontsize=9); grid(ax_p)

    ax_t.yaxis.set_major_formatter(fmt_k)
    ax_t.set_title("Annual Tax + Healthcare by Scenario", fontsize=11, fontweight="bold")
    ax_t.set_xlabel("Age"); ax_t.set_ylabel("Tax + Healthcare ($)")
    ax_t.legend(fontsize=9); grid(ax_t)

    plt.tight_layout()
    #save_chart(fig, "chart3_percentile_paths.png", 3)
    return fig


# =============================================================================
# SECTION 18 — CHART 4: SCENARIO COMPARISON (SUBSIDIZED vs NO-SUBSIDY ACA)
# =============================================================================

def chart4_comparison(df_a, df_b, sum_a, sum_b, label_a, label_b):
    """
    Four-panel side-by-side comparison of Scenario A (subsidized ACA) vs
    Scenario B (no ACA subsidy / full-price ACA).

    Panel A — Median portfolio:   shows overall wealth trajectory
    Panel B — Roth conversions:   shows how much larger conversions are when
                                  the ACA surcharge is removed (ages 60–64)
    Panel C — IRA balance:        shows faster IRA depletion under no-subsidy,
                                  which reduces future RMDs and tax burden
    Panel D — Tax + healthcare:   shows whether larger upfront conversions
                                  reduce the late-life tax spike from RMDs

    Blue = Scenario A (Subsidized ACA)
    Red  = Scenario B (No ACA Subsidy)
    """
    fig, axes = plt.subplots(2, 2, figsize=(16, 12))
    fig.patch.set_facecolor("#F8F9FA")
    fig.suptitle(f"Scenario Comparison: {label_a}  vs.  {label_b}",
                 fontsize=14, fontweight="bold", y=0.98)

    colors = {label_a: C_BLUE, label_b: C_RED}
    for ax in axes.flat: ax.set_facecolor("#F8F9FA")

    # ── Panel A: Median portfolio path ───────────────────────────────────────
    ax = axes[0, 0]
    for df, lbl in [(df_a, label_a), (df_b, label_b)]:
        med = df.groupby("Age")["Portfolio"].median()
        ax.plot(med.index, med.values, color=colors[lbl], lw=2.2, label=lbl)
    ax.yaxis.set_major_formatter(fmt_m)
    ax.set_title("Median Portfolio Value", fontsize=11, fontweight="bold")
    ax.set_xlabel("Age"); ax.set_ylabel("Portfolio (Real 2025 $)")
    ax.legend(fontsize=9); grid(ax); add_milestones(ax)
    ax.set_xlim(START_AGE, END_AGE)

    # ── Panel B: Annual Roth conversion ──────────────────────────────────────
    # Bars are offset side-by-side for clarity.
    # The key difference appears at ages 60–64: no-subsidy converts much more.
    ax = axes[0, 1]
    for df, lbl in [(df_a, label_a), (df_b, label_b)]:
        med = df.groupby("Age")["Roth Conv"].median()
        ax.bar(med.index + (-0.35 if lbl == label_a else 0.35),
               med.values, width=0.65, color=colors[lbl], alpha=0.8, label=lbl)
    ax.yaxis.set_major_formatter(fmt_k)
    ax.set_title("Annual Roth Conversion (Median)", fontsize=11, fontweight="bold")
    ax.set_xlabel("Age"); ax.set_ylabel("Conversion Amount ($)")
    ax.legend(fontsize=9); grid(ax)
    ax.set_xlim(START_AGE-0.5, 74.5)   # zoom to the conversion window only

    # ── Panel C: IRA balance over time ───────────────────────────────────────
    # Lower IRA under no-subsidy = smaller future RMDs = lower tax burden at 73+
    ax = axes[1, 0]
    for df, lbl in [(df_a, label_a), (df_b, label_b)]:
        med = df.groupby("Age")["IRA"].median()
        ax.plot(med.index, med.values, color=colors[lbl], lw=2.2, label=lbl)
    ax.yaxis.set_major_formatter(fmt_m)
    ax.set_title("Median IRA Balance (drives future RMDs)", fontsize=11, fontweight="bold")
    ax.set_xlabel("Age"); ax.set_ylabel("IRA Balance (Real $)")
    ax.legend(fontsize=9); grid(ax); add_milestones(ax)
    ax.set_xlim(START_AGE, END_AGE)

    # ── Panel D: Annual tax + healthcare ─────────────────────────────────────
    ax = axes[1, 1]
    for df, lbl in [(df_a, label_a), (df_b, label_b)]:
        med_tax    = df.groupby("Age")["Tax"].median()
        med_health = df.groupby("Age")["Health"].median()
        ages_arr   = med_tax.index
        ax.bar(ages_arr + (-0.35 if lbl == label_a else 0.35),
               (med_tax + med_health).values, width=0.65,
               color=colors[lbl], alpha=0.8, label=f"{lbl}")
    ax.yaxis.set_major_formatter(fmt_k)
    ax.set_title("Annual Tax + Healthcare (Median)", fontsize=11, fontweight="bold")
    ax.set_xlabel("Age"); ax.set_ylabel("Annual Cost ($)")
    ax.legend(fontsize=9); grid(ax); add_milestones(ax)
    ax.set_xlim(START_AGE-0.5, END_AGE+0.5)

    plt.tight_layout()
    #save_chart(fig, "chart4_comparison.png", 4)
    return fig


# =============================================================================
# SECTION 19 — SUMMARY STATISTICS PRINTER
# =============================================================================

def print_comparison(df_med_a, sum_a, label_a, df_med_b, sum_b, label_b):
    """
    Print a side-by-side summary table comparing the median path outcomes
    across both scenarios.  Shows terminal portfolio, Roth conversions,
    healthcare costs, lifetime tax burden, and survival rates.
    """
    print()
    print("=" * 72)
    print("  SCENARIO COMPARISON — MEDIAN PATH  (Real 2025 $)")
    print(f"  {'Metric':<40} {label_a:>14}  {label_b:>14}")
    print("=" * 72)

    rows = [
        ("Terminal portfolio (age 95)",     df_med_a.iloc[-1]["Portfolio"],  df_med_b.iloc[-1]["Portfolio"]),
        ("  of which IRA",                  df_med_a.iloc[-1]["IRA"],        df_med_b.iloc[-1]["IRA"]),
        ("  of which Roth",                 df_med_a.iloc[-1]["Roth"],       df_med_b.iloc[-1]["Roth"]),
        ("Total Roth conversions",          df_med_a["Roth Conv"].sum(),     df_med_b["Roth Conv"].sum()),
        ("Healthcare paid (pre-65 only)",   df_med_a[df_med_a["Age"]<65]["Health"].sum(),
                                            df_med_b[df_med_b["Age"]<65]["Health"].sum()),
        ("Total lifetime tax+health",       df_med_a["Tax"].sum()+df_med_a["Health"].sum(),
                                            df_med_b["Tax"].sum()+df_med_b["Health"].sum()),
        ("Peak annual tax+health",         (df_med_a["Tax"]+df_med_a["Health"]).max(),
                                           (df_med_b["Tax"]+df_med_b["Health"]).max()),
    ]

    for label, va, vb in rows:
        diff = vb - va
        sign = "+" if diff >= 0 else ""
        print(f"  {label:<40} ${va:>13,.0f}  ${vb:>13,.0f}  ({sign}${diff:,.0f})")

    print()
    print("  SURVIVAL RATES  (% of 2,000 simulations still solvent)")
    for chk in [75, 80, 85, 90, 95]:
        ra = sum_a[sum_a["Age"] == chk]
        rb = sum_b[sum_b["Age"] == chk]
        if not ra.empty and not rb.empty:
            print(f"  Age {chk}: {ra['Survival'].values[0]:.1%}  vs  {rb['Survival'].values[0]:.1%}")
    print("=" * 72)


# =============================================================================
# SECTION 20 — MAIN: RUN BOTH SCENARIOS AND PRODUCE ALL OUTPUTS
# =============================================================================

# =============================================================================
# =============================================================================
# SECTION 19 — CHART 5: GRID ANALYSIS
# =============================================================================

def chart5_grid(grid_df):
    """
    Six-panel grid analysis chart showing how Roth conversion effectiveness
    varies across different starting IRA and taxable account balances.

    Panels:
      1 — Total Roth conversions ($M) by IRA size, colored by taxable balance
      2 — Portfolio survival rate at END_AGE (heatmap, green=high)
      3 — Terminal portfolio at END_AGE ($M) by IRA size
      4 — Total RMD tax paid ages 75+ ($M, heatmap, red=high)
      5 — Whether IRA is fully converted before RMDs at 75 (green/red)
      6 — Lifetime tax + healthcare ($M) by IRA size

    Parameters:
        grid_df  — DataFrame with one row per (taxable, ira) cell containing:
                   total_conv, terminal_port, total_rmd_tax,
                   total_tax_health, survival_pct, ira_depleted
    """
    import matplotlib.colors as mcolors

    tax_vals = sorted(grid_df['taxable'].unique())
    ira_vals = sorted(grid_df['ira'].unique())
    ira_labels = [f"${v//1_000_000}M" for v in ira_vals]
    tax_labels = [f"${v//1_000_000}M" for v in tax_vals]

    def _fmt(v):
        """Format a dollar value in millions, e.g. 500000 → '$0.5M', 1000000 → '$1M'."""
        m = v / 1_000_000
        return f"${m:.1f}M" if m != int(m) else f"${int(m)}M"

    def make_pivot(col, scale=1.0):
        """Return a pivot table indexed by IRA label, columns by taxable label."""
        d = grid_df.copy()
        p = d.pivot(index='ira', columns='taxable', values=col) / scale
        p.index   = [f"${v//1_000_000}M" for v in p.index]
        p.columns = [f"${v//1_000_000}M" for v in p.columns]
        return p

    pv_conv    = make_pivot('total_conv',       1_000_000)
    pv_surv    = make_pivot('survival_pct')
    pv_port    = make_pivot('terminal_port',    1_000_000)
    pv_rmd     = make_pivot('total_rmd_tax',    1_000_000)
    pv_deplete = make_pivot('ira_depleted')
    pv_tth     = make_pivot('total_tax_health', 1_000_000)

    line_colors  = [C_BLUE, C_GREEN, C_RED, C_ORANGE]
    line_markers = ['o', 's', '^', 'D']

    fig = plt.figure(figsize=(18, 20))
    fig.patch.set_facecolor('#F8F9FA')
    gs = GridSpec(3, 2, figure=fig, hspace=0.46, wspace=0.35)
    axes = [fig.add_subplot(gs[r, c]) for r in range(3) for c in range(2)]
    for ax in axes:
        ax.set_facecolor('#F8F9FA')

    def gridlines(ax):
        ax.grid(True, color=GRID_CLR, linestyle='--', linewidth=0.6, alpha=0.7)
        ax.set_axisbelow(True)

    # ── Panel 1: Total Roth conversions (line chart) ──────────────────────────
    ax = axes[0]
    for j, (tax_val, color, marker) in enumerate(zip(tax_vals, line_colors, line_markers)):
        tlab = _fmt(tax_val)
        ax.plot(ira_labels, pv_conv.iloc[:, j].values,
                color=color, lw=2.0, marker=marker, ms=7,
                label=f"Taxable {tlab}")
    ax.set_title("Total Roth Conversions (Median Path)", fontsize=11, fontweight='bold')
    ax.set_xlabel("Starting IRA Balance"); ax.set_ylabel("Total Conversions ($M)")
    ax.yaxis.set_major_formatter(FuncFormatter(lambda x, _: f"${x:.1f}M"))
    ax.legend(fontsize=9); gridlines(ax)

    # ── Panel 2: Survival rate (heatmap) ─────────────────────────────────────
    ax = axes[1]
    im = ax.imshow(pv_surv.values, cmap=plt.cm.RdYlGn,
                   vmin=0, vmax=100, aspect='auto')
    ax.set_xticks(range(len(tax_labels))); ax.set_xticklabels(tax_labels)
    ax.set_yticks(range(len(ira_labels))); ax.set_yticklabels(ira_labels)
    ax.set_xlabel("Taxable Account"); ax.set_ylabel("IRA Balance")
    ax.set_title(f"Portfolio Survival Rate at Age {END_AGE} (%)",
                 fontsize=11, fontweight='bold')
    for i in range(len(ira_vals)):
        for j in range(len(tax_vals)):
            val = float(pv_surv.iloc[i, j])
            ax.text(j, i, f"{val:.0f}%", ha='center', va='center',
                    fontsize=9, fontweight='bold',
                    color='white' if (val < 35 or val > 80) else '#222')
    plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)

    # ── Panel 3: Terminal portfolio (line chart) ───────────────────────────────
    ax = axes[2]
    for j, (tax_val, color, marker) in enumerate(zip(tax_vals, line_colors, line_markers)):
        tlab = _fmt(tax_val)
        ax.plot(ira_labels, pv_port.iloc[:, j].values,
                color=color, lw=2.0, marker=marker, ms=7,
                label=f"Taxable {tlab}")
    ax.set_title(f"Terminal Portfolio at Age {END_AGE} (Median Path)",
                 fontsize=11, fontweight='bold')
    ax.set_xlabel("Starting IRA Balance"); ax.set_ylabel("Terminal Portfolio ($M)")
    ax.yaxis.set_major_formatter(FuncFormatter(lambda x, _: f"${x:.0f}M"))
    ax.legend(fontsize=9); gridlines(ax)

    # ── Panel 4: Total RMD tax (heatmap) ─────────────────────────────────────
    ax = axes[3]
    im2 = ax.imshow(pv_rmd.values, cmap=plt.cm.YlOrRd, aspect='auto')
    ax.set_xticks(range(len(tax_labels))); ax.set_xticklabels(tax_labels)
    ax.set_yticks(range(len(ira_labels))); ax.set_yticklabels(ira_labels)
    ax.set_xlabel("Taxable Account"); ax.set_ylabel("IRA Balance")
    ax.set_title("Total RMD Tax Paid — Ages 75+ (Median Path)",
                 fontsize=11, fontweight='bold')
    max_rmd = pv_rmd.values.max() if pv_rmd.values.max() > 0 else 1.0
    for i in range(len(ira_vals)):
        for j in range(len(tax_vals)):
            val = float(pv_rmd.iloc[i, j])
            ax.text(j, i, f"${val:.1f}M", ha='center', va='center',
                    fontsize=8.5, fontweight='bold',
                    color='white' if val > max_rmd * 0.6 else '#222')
    plt.colorbar(im2, ax=ax, fraction=0.046, pad=0.04)

    # ── Panel 5: IRA depleted before RMDs (green/red heatmap) ────────────────
    ax = axes[4]
    cmap_dep = mcolors.ListedColormap(['#C0504D', '#2E7D32'])
    ax.imshow(pv_deplete.values.astype(float),
              cmap=cmap_dep, vmin=0, vmax=1, aspect='auto')
    ax.set_xticks(range(len(tax_labels))); ax.set_xticklabels(tax_labels)
    ax.set_yticks(range(len(ira_labels))); ax.set_yticklabels(ira_labels)
    ax.set_xlabel("Taxable Account"); ax.set_ylabel("IRA Balance")
    ax.set_title(f"IRA Fully Converted Before RMDs at {RMD_START_AGE}?",
                 fontsize=11, fontweight='bold')
    for i in range(len(ira_vals)):
        for j in range(len(tax_vals)):
            depleted = bool(float(pv_deplete.iloc[i, j]))
            ax.text(j, i, "YES ✓" if depleted else "NO ✗",
                    ha='center', va='center', fontsize=9,
                    fontweight='bold', color='white')
    yes_p = mpatches.Patch(color='#2E7D32', label='YES — IRA depleted, no forced RMDs')
    no_p  = mpatches.Patch(color='#C0504D', label='NO — RMD residual remains at 75')
    ax.legend(handles=[yes_p, no_p], loc='upper center',
              bbox_to_anchor=(0.5, -0.14), fontsize=8.5, ncol=2)

    # ── Panel 6: Lifetime tax + healthcare (line chart) ───────────────────────
    ax = axes[5]
    for j, (tax_val, color, marker) in enumerate(zip(tax_vals, line_colors, line_markers)):
        tlab = _fmt(tax_val)
        ax.plot(ira_labels, pv_tth.iloc[:, j].values,
                color=color, lw=2.0, marker=marker, ms=7,
                label=f"Taxable {tlab}")
    ax.set_title("Lifetime Tax + Healthcare (Median Path)",
                 fontsize=11, fontweight='bold')
    ax.set_xlabel("Starting IRA Balance"); ax.set_ylabel("Lifetime Cost ($M)")
    ax.yaxis.set_major_formatter(FuncFormatter(lambda x, _: f"${x:.1f}M"))
    ax.legend(fontsize=9); gridlines(ax)

    aca_note = ("Original ACA 2026+ (400% FPL cliff)"
                if not USE_ACA_SUBSIDY else "Enhanced ACA (expired 2025)")
    fig.suptitle(
        f"Roth Conversion Grid Analysis\n"
        f"Taxable ${min(tax_vals)//1_000_000}M–${max(tax_vals)//1_000_000}M  ×  "
        f"IRA ${min(ira_vals)//1_000_000}M–${max(ira_vals)//1_000_000}M  |  "
        f"MARGINAL_STOP={MARGINAL_STOP:.0%}  |  {aca_note}  |  SIMS={GRID_SIMS}",
        fontsize=12, fontweight='bold', y=0.995)

    path = os.path.abspath("chart5_grid_analysis.png")
    try:
        plt.savefig(path, dpi=150, bbox_inches='tight')
        print(f"Chart 5 (grid analysis) saved: {path}")
    except Exception as e:
        print(f"Chart 5 FAILED: {e}")
    finally:
        plt.close(fig)
    return fig


def _run_grid_analysis():
    """
    Sweep across GRID_TAXABLE × GRID_IRA combinations and return a
    DataFrame of per-cell summary metrics. Called from main() when
    RUN_GRID_ANALYSIS = True.

    Temporarily overrides SIMS, IRA_START, and TAXABLE_START for each
    cell then restores the original values on completion.
    """
    import time as _time

    original_sims     = SIMS
    original_ira      = IRA_START
    original_taxable  = TAXABLE_START

    n_cells = len(GRID_TAXABLE) * len(GRID_IRA)
    print(f"\nGrid analysis: {len(GRID_TAXABLE)} taxable levels × "
          f"{len(GRID_IRA)} IRA levels = {n_cells} cells × {GRID_SIMS} sims each...")

    rows = []
    t0 = _time.time()
    for taxable in GRID_TAXABLE:
        for ira in GRID_IRA:
            globals()["SIMS"]          = GRID_SIMS
            globals()["IRA_START"]     = ira
            globals()["TAXABLE_START"] = taxable

            df = run_simulation()

            # Median path (stable sort excluding Roth — invariant to ROTH_START)
            non_roth = (df.groupby("Sim")[["Portfolio", "Roth"]].last()
                        .eval("NonRoth = Portfolio - Roth")["NonRoth"]
                        .sort_values())
            med_id = non_roth.index[len(non_roth) // 2]
            med    = df[df["Sim"] == med_id].copy()

            rows.append(dict(
                taxable          = taxable,
                ira              = ira,
                total_conv       = med["Roth Conv"].sum(),
                terminal_port    = med.iloc[-1]["Portfolio"],
                terminal_ira     = med.iloc[-1]["IRA"],
                terminal_roth    = med.iloc[-1]["Roth"],
                total_rmd_tax    = med[med["Age"] >= RMD_START_AGE]["Tax"].sum(),
                total_tax_health = med["Tax"].sum() + med["Health"].sum(),
                survival_pct     = (df[df["Age"] == END_AGE]["Portfolio"] > 0).mean() * 100,
                ira_depleted     = med.iloc[-1]["IRA"] < 10_000,
            ))
            r = rows[-1]
            print(f"  Taxable=${taxable//1_000_000}M  IRA=${ira//1_000_000}M  "
                  f"Conv=${r['total_conv']/1e6:4.1f}M  "
                  f"Port=${r['terminal_port']/1e6:5.1f}M  "
                  f"Surv={r['survival_pct']:4.1f}%  "
                  f"{'✓ depleted' if r['ira_depleted'] else '○ RMDs remain':>12}")

    # Restore original module-level values
    globals()["SIMS"]          = original_sims
    globals()["IRA_START"]     = original_ira
    globals()["TAXABLE_START"] = original_taxable

    print(f"Grid complete in {_time.time()-t0:.0f}s")
    return pd.DataFrame(rows)


# HELPERS for main()
# =============================================================================

def _build_summary(df):
    """Percentile summary and survival rate at each age."""
    return df.groupby("Age")["Portfolio"].agg(
        P10      = lambda x: np.percentile(x, 10),
        P25      = lambda x: np.percentile(x, 25),
        Median   = "median",
        Mean     = "mean",
        P75      = lambda x: np.percentile(x, 75),
        P90      = lambda x: np.percentile(x, 90),
        Survival = lambda x: (x > 0).mean(),
    ).reset_index()


def _build_median_df(df):
    """Select the simulation whose non-Roth terminal value is at the median."""
    non_roth = (df.groupby("Sim")[["Portfolio", "Roth"]].last()
                .eval("NonRoth = Portfolio - Roth")["NonRoth"]
                .sort_values())
    med_id = non_roth.index[len(non_roth) // 2]
    return df[df["Sim"] == med_id].copy()


def _write_excel(sheets, params_rows):
    """Write workbook with given sheets plus a Parameters tab."""
    if os.path.exists(os.path.abspath(OUTPUT_FILE)):
        os.remove(os.path.abspath(OUTPUT_FILE))
    with pd.ExcelWriter(OUTPUT_FILE, engine="openpyxl") as w:
        for sheet_name, frame in sheets:
            frame.to_excel(w, sheet_name=sheet_name, index=False)
        pd.DataFrame(params_rows, columns=["Parameter", "Value"]).to_excel(
            w, sheet_name="Parameters", index=False)
    print(f"Excel saved: {os.path.abspath(OUTPUT_FILE)}")


def _print_single_summary(df_med, summary, label):
    """Print key stats for a single-scenario run."""
    fin = df_med.iloc[-1]
    print()
    print("=" * 58)
    print(f"  KEY RESULTS — {label}")
    print("=" * 58)
    print(f"  Terminal portfolio at {END_AGE}:   ${fin['Portfolio']:>14,.0f}")
    print(f"    IRA:                           ${fin['IRA']:>14,.0f}")
    print(f"    Roth:                          ${fin['Roth']:>14,.0f}")
    print(f"  Total Roth conversions:          ${df_med['Roth Conv'].sum():>14,.0f}")
    peak = df_med.loc[(df_med["Tax"] + df_med["Health"]).idxmax()]
    print(f"  Peak annual tax+health:          ${peak['Tax']+peak['Health']:>14,.0f}"
          f"  (age {int(peak['Age'])})")
    print("  SURVIVAL RATES")
    for chk in [75, 80, 85, 90, 95]:
        row = summary[summary["Age"] == chk]
        if not row.empty:
            print(f"  Age {chk}: {row['Survival'].values[0]:.1%}  "
                  f"(median ${row['Median'].values[0]:>12,.0f})")
    print("=" * 58)


# =============================================================================
# SECTION 20 — MAIN
# =============================================================================

if __name__ == "__main__":
    import time

    valid_modes = ("aca_comparison", "single_enhanced", "single_original")
    if SCENARIO_MODE not in valid_modes:
        raise ValueError(
            f"SCENARIO_MODE='{SCENARIO_MODE}' is not valid. "
            f"Choose one of: {valid_modes}"
        )

    base_params = [
        ("", ""),
        ("SCENARIO_MODE",        SCENARIO_MODE),
        ("Initial Cash",         CASH_START),
        ("Initial Taxable",      TAXABLE_START),
        ("Initial IRA",          IRA_START),
        ("Initial Roth IRA",     ROTH_START),
        ("Mean Real Return",     MEAN_RETURN),
        ("Return Volatility",    VOL_RETURN),
        ("Crash Floor",          CRASH_FLOOR),
        ("Dividend Yield",       DIV_YIELD),
        ("Cost Basis %",         COST_BASIS_PCT),
        ("Qualified Div %",      QUAL_DIV_PCT),
        ("Base Expenses",        BASE_EXPENSES),
        ("Inflation (brackets)", INFLATION),
        ("SS Start Age",         SS_START_AGE),
        ("SS Amount",            SS_AMOUNT),
        ("Roth End Age",         ROTH_END_AGE),
        ("Marginal Stop",        MARGINAL_STOP),
        ("Benchmark Premium",    BENCHMARK_PREMIUM),
        ("Medicare Base",        MEDICARE_BASE),
        ("Simulations",          SIMS),
        ("Random Seed",          SEED),
    ]

    # ──────────────────────────────────────────────────────────────────────────
    if SCENARIO_MODE == "aca_comparison":
        print("SCENARIO_MODE = 'aca_comparison'  (running both ACA regimes)")
        print(f"Running Scenario A: Enhanced ACA — 2021-2025 expired rules ({SIMS:,} sims)...")
        globals()["USE_ACA_SUBSIDY"] = True
        t0 = time.time(); df_a = run_simulation(); print(f"  Done in {time.time()-t0:.0f}s")

        print(f"Running Scenario B: Original ACA — 2026+ rules ({SIMS:,} sims)...")
        globals()["USE_ACA_SUBSIDY"] = False
        t0 = time.time(); df_b = run_simulation(); print(f"  Done in {time.time()-t0:.0f}s")

        sum_a = _build_summary(df_a);    df_med_a = _build_median_df(df_a)
        sum_b = _build_summary(df_b);    df_med_b = _build_median_df(df_b)
        label_a = "Enhanced ACA (2025)"
        label_b = "Original ACA (2026+)"

        print("Building charts and Excel...")
        chart1_fan(sum_a)
        chart2_median(df_med_a,
                      filename="chart2_median_enhanced_aca.png",
                      subtitle="Enhanced ACA — 2021-2025 expired rules")
        chart2_median(df_med_b,
                      filename="chart2_median_original_aca.png",
                      subtitle="Original ACA — 2026+ rules (400% FPL cliff)")
        chart3_paths(df_a)
        chart4_comparison(df_a, df_b, sum_a, sum_b, label_a, label_b)
        print_comparison(df_med_a, sum_a, label_a, df_med_b, sum_b, label_b)

        _write_excel(
            sheets=[
                ("Summary (Enhanced ACA)",  sum_a),
                ("Median Path (Enhanced)",  df_med_a),
                ("Summary (Original ACA)",  sum_b),
                ("Median Path (Original)",  df_med_b),
            ],
            params_rows=[
                ("SCENARIO A", "Enhanced ACA — 2021-2025 expired rules"),
                ("SCENARIO B", "Original ACA — 2026+ rules (400% FPL cliff)"),
            ] + base_params,
        )
        if RUN_GRID_ANALYSIS:
            grid_df = _run_grid_analysis()
            chart5_grid(grid_df)

    # ──────────────────────────────────────────────────────────────────────────
    elif SCENARIO_MODE == "single_enhanced":
        globals()["USE_ACA_SUBSIDY"] = True
        label   = "Enhanced ACA — 2021-2025 expired rules"
        print(f"SCENARIO_MODE = 'single_enhanced'")
        print(f"Running: {label}  ({SIMS:,} sims)...")
        t0 = time.time(); df = run_simulation(); print(f"  Done in {time.time()-t0:.0f}s")
        summary = _build_summary(df); df_med = _build_median_df(df)
        print("Building charts and Excel...")
        chart1_fan(summary)
        chart2_median(df_med, filename="chart2_median_enhanced_aca.png",
                      subtitle="Enhanced ACA — 2021-2025 expired rules")
        chart3_paths(df)
        _print_single_summary(df_med, summary, label)
        _write_excel(
            sheets=[("Summary", summary), ("Median Path", df_med)],
            params_rows=[("SCENARIO", label)] + base_params,
        )
        if RUN_GRID_ANALYSIS:
            grid_df = _run_grid_analysis()
            chart5_grid(grid_df)

    # ──────────────────────────────────────────────────────────────────────────
    elif SCENARIO_MODE == "single_original":
        globals()["USE_ACA_SUBSIDY"] = False
        label   = "Original ACA — 2026+ rules (400% FPL cliff)"
        print(f"SCENARIO_MODE = 'single_original'")
        print(f"Running: {label}  ({SIMS:,} sims)...")
        t0 = time.time(); df = run_simulation(); print(f"  Done in {time.time()-t0:.0f}s")
        summary = _build_summary(df); df_med = _build_median_df(df)
        print("Building charts and Excel...")
        chart1_fan(summary)
        chart2_median(df_med, filename="chart2_median_original_aca.png",
                      subtitle="Original ACA — 2026+ rules (400% FPL cliff)")
        chart3_paths(df)
        _print_single_summary(df_med, summary, label)
        _write_excel(
            sheets=[("Summary", summary), ("Median Path", df_med)],
            params_rows=[("SCENARIO", label)] + base_params,
        )
        if RUN_GRID_ANALYSIS:
            grid_df = _run_grid_analysis()
            chart5_grid(grid_df)
